# -*- coding: utf-8 -*-
"""streamlit final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JRIG8jVIsPF4x3kz149WJzeILvzU81WD
"""

pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py

! wget -q -O - ipv4.icanhazip.com

! streamlit run app.py & npx localtunnel --port 8501

